### DISCUSSION TITLE
Solar Monitor einrichten

### DISCUSSION THREAD

**Discussion by checkersky** [ohAnd/dtuGateway#86] [Q&A] [answered]
Hallo,

ich würde das DTU gateway als Solar Monitor nutzen bekomme es aber nicht hin... 

laut Anleitung brauche ich: "/PV_Power_Sum/state and for the yield of the day /PV_Energy_Sum_Day/state "
Aber wie richte ich das Home Assistant ein ?

Wäre es eventuell möglich das man einfach in den dtuGateway setings die Entität eingibt und das gateway zeigt den wert dann an ?

**Comment by ohAnd** [comment, marked as answer]
Hi,

habs mal in kurzer Form in HA automations versucht und getestet:

```yaml
alias: Test SumPower
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.openhab_mqtt_pv_system_pv_leistung_gesamt
conditions: []
actions:
  - action: mqtt.publish
    metadata: {}
    data:
      evaluate_payload: false
      qos: "0"
      topic: /TEST_PV_Power_Sum/state
      payload: "{{ states('sensor.openhab_mqtt_pv_system_pv_leistung_gesamt') }}"
mode: single
```

1. Also neue automation anlegen
2. Trigger ist ein Zustandswechsel der Entity die die aktuelle Gesamt PV-Leistung enthält
3. Aktion ist MQTT publish
4. In der Konfiguration dann als Payload in `{{ states('...') }}` den triggernden Sensor angeben

Dann wird mit jeder Änderung der Wert auf die erwartete Ziel-Topic geschrieben.

D.h. für dtuGateway mit PV Summen Anzeige z.B.:

- Basis Config für MQTT wie gehabt
- MQTT MainTopic `PVdisplay`

in HA automation dann:
 ```yaml
alias: PV Sum Power
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.<<your_sensor>>
conditions: []
actions:
  - action: mqtt.publish
    metadata: {}
    data:
      evaluate_payload: false
      qos: "0"
      topic: PVdisplay/PV_Power_Sum/state
      payload: "{{ states('sensor.<<your_sensor>>') }}"
mode: single
```
Das Ganze dann nochmal für den Tagesertrag gesamt als weitere Automation anlegen.

...

Die Erweiterung in dtuGateway mit entsprechender Angabe einer (zweier) spezfischen Topic habe ich mir vom Aufwand erstmal gespart, da bei mir eine andere konfigurierbare Quelle die Daten im Ziel-Topic an MQTT gibt...
Mglw. kann ich das später mal angehen.
